---

- name: create bash aliases
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { src: "bash/00-aliases.sh", dest: "/etc/profile.d/00-aliases.sh", owner: "root", group: "root", mode: "0644" }
