---

- name: update-locale
  command: "update-locale LANG={{ system_locale }}"

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: postmap sasl_passwd
  command: postmap hash:/etc/postfix/sasl_passwd

- name: postfix new aliases
  command: newaliases

- name: restart sshd
  service:
    name: ssh
    state: restarted

- name: reload ufw
  ufw:
    state: reloaded

- name: reboot host
  reboot:
